### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by ErikPDev** [NgLamVN/YandereDevStyle#3]
How long did it took you to make this lmao

**Comment by AGTHARN** [comment]
now this is **ART**

**Comment by NgLam2911** [comment]
> How long did it took you to make this lmao

I just generate a whole of code using C++

**Comment by ErikPDev** [comment]
Interesting, So you can generate 2000 times rather than 1000?

**Comment by NgLam2911** [comment]
> Interesting, So you can generate 2000 times rather than 1000?

hmmm i think 1000 is enough but u can extend it if u want lol.

**Comment by ErikPDev** [comment]
i have evil plans

**Comment by ErikPDev** [comment]
but that's for later, working on an update for AdvanceDeaths lol
